services:
  db:
    image: postgres:15.6-alpine
    container_name: smart_home_db
    restart: unless-stopped
    shm_size: 512mb
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - smart_home_network

  bot:
    build: .
    container_name: smart_home_bot
    restart: unless-stopped
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: 5432
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - db
    networks:
      - smart_home_network
    command: >
      bash -c "
        alembic upgrade head &&
        python3 -m bot.main
      "

volumes:
  db_data:

networks:
  smart_home_network:
    driver: bridge
